services:
  chroma:
    image: harbor.bigdata.com/chatbi/chromadb/chroma:0.5.3
    privileged: true
    container_name: chatbi_chroma
    ports:
      - "8000:8000"
    volumes:
      - chatbi_chroma_data:/chroma
    networks:
      - chatbi_network
    dns:
      - 114.114.114.114
      - 8.8.8.8
      - 8.8.4.4
    healthcheck:
      test: ["CMD", "curl", "http://0.0.0.0:8000"]
      interval: 10s
      timeout: 5s
      retries: 10

  mysql:
    image: harbor.bigdata.com/chatbi/mysql:8.0
    privileged: true
    container_name: chatbi_mysql
    environment:
      LANG: 'C.UTF-8'  # 设置环境变量
      MYSQL_ROOT_PASSWORD: Xmz@323!
      MYSQL_DATABASE: chatbi_db
      MYSQL_USER: chatbi_user
      MYSQL_PASSWORD: Xmz@323!
    ports:
      - "13306:3306"
    volumes:
      - chatbi_mysql_data:/var/lib/mysql
    networks:
      - chatbi_network
    dns:
      - 114.114.114.114
      - 8.8.8.8
      - 8.8.4.4
    depends_on:
      chroma:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  db_init:
    image: harbor.bigdata.com/chatbi/supersonic:${SUPERSONIC_VERSION:-latest}
    privileged: true
    container_name: chatbi_db_init
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - chatbi_network
    command: >
      sh -c "
      sleep 15 &&
      if ! mysql -h chatbi_mysql -uchatbi_user -pXmz@323! -e 'use chatbi_db; show tables;' | grep -q 's2_database'; then
        mysql -h chatbi_mysql -uchatbi_user -pXmz@323! chatbi_db < /usr/src/app/supersonic-standalone-${SUPERSONIC_VERSION:-latest}/conf/db/schema-mysql.sql &&
        mysql -h chatbi_mysql -uchatbi_user -pXmz@323! chatbi_db < /usr/src/app/supersonic-standalone-${SUPERSONIC_VERSION:-latest}/conf/db/data-mysql.sql
      else
        echo 'Database already initialized.'
      fi
      "
    dns:
      - 114.114.114.114
      - 8.8.8.8
      - 8.8.4.4

  chatbi_standalone:
    image: harbor.bigdata.com/chatbi/supersonic:${SUPERSONIC_VERSION:-latest}
    privileged: true
    container_name: chatbi_standalone
    environment:
      DB_HOST: chatbi_mysql
      DB_NAME: chatbi_db
      DB_USERNAME: chatbi_user
      DB_PASSWORD: Xmz@323!
      CHROMA_HOST: chatbi_chroma
    ports:
      - "9080:9080"
    depends_on:
      chroma:
        condition: service_healthy
      mysql:
        condition: service_healthy
      db_init:
        condition: service_completed_successfully
    networks:
      - chatbi_network
    dns:
      - 114.114.114.114
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      #1.Named Volumes are best for persistent data managed by Docker.
      - chatbi_standalone:/usr/src/app/supersonic-standalone-${SUPERSONIC_VERSION:-latest}
      #2.Bind Mounts are suitable for frequent modifications and debugging.
      #      - ./conf/application-prd.yaml:/usr/src/app/supersonic-standalone-${SUPERSONIC_VERSION:-latest}/conf/application-prd.yaml
      #3.Detailed Bind Mounts offer more control over the mount behavior.
      #      - type: bind
      #        source: ./supersonic-standalone-${SUPERSONIC_VERSION:-latest}/logs
      #        target: /usr/src/app/supersonic-standalone-${SUPERSONIC_VERSION:-latest}/logs
      #        bind:
      #          propagation: rprivate
      #          create_host_path: true
volumes:
  chatbi_mysql_data:
  chatbi_chroma_data:
  chatbi_standalone:

networks:
  chatbi_network: