# Use an official OpenJDK runtime as a parent image
FROM harbor.bigdata.com/chatbi/openjdk:8-jdk

# Install necessary packages, including MySQL client
RUN apt-get update && \
    apt-get install -y default-mysql-client unzip && \
    rm -rf /var/lib/apt/lists/*

# Install the vim editor.
RUN apt-get update && \
    apt-get install -y vim && \
    rm -rf /var/lib/apt/lists/*

# Update the package list and install iputils-ping.
RUN apt-get update && apt-get install -y iputils-ping

# 更新包列表并安装 dnsutils 包
RUN apt-get update && apt-get install -y dnsutils