spring:
  datasource:
    url: jdbc:mysql://172.19.230.204:3306/supersonic096?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true
    username: root
    password: Xmz@323!
    driver-class-name: com.mysql.jdbc.Driver